# Generated by Django 5.2.8 on 2025-12-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Код ресурса (например: financial_reports)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание ресурса')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False, help_text='POST')),
                ('can_read', models.BooleanField(default=False, help_text='GET')),
                ('can_update', models.BooleanField(default=False, help_text='PUT/PATCH')),
                ('can_delete', models.BooleanField(default=False, help_text='DELETE')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.resource')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
    ]
